### ISSUE TITLE
sendMessage kan NullPointerException veroorzaken in LunchMessager

### ISSUE THREAD

**Issue by Zelzahn** [DaanWet/DnD_Discord_Bot#7]

**Comment by DaanWet** [comment]
Ja mijn IDE zegt da ook ma kdenk da da is als het channel nie bestaat, ma da zou normaal nie kunnen want ik check da dervoor. Maar dat ben ik ook niet zeker

**Comment by Zelzahn** [comment]
Aight dus negeren die handel.
